#! /bin/sh

### AUTOSTART ###
pkill sxhkd; sxhkd &
nitrogen --restore &
#pkill xfce4-power-manager; xfce4-power-manager &
nm-applet &
xset fp+ ~/.font/misc &
xsetroot -cursor_name left_ptr &
~/.config/bspwm/panel.sh &
#~/.config/polybar/launch.sh &

### MONITORS ###
bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor LVDS1 -d 1 2 3 4 5 6 
#bspc monitor VGA1 -d 7

### CONFIG ###
bspc config border_width                1
bspc config window_gap                  8
bspc config top_padding                 25
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config single_monocle              false
bspc config click_to_focus              true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       false
bspc config history_aware_focus         true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

### COLORING ###
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#1e1e1e"
bspc config focused_border_color        "#5e81ac"
bspc config presel_feedback_color       "#5e81ac"
bspc config urgent_border_color         "#dd2727"

### WINDOWS-RULES ###
bspc rule -a firefox -o desktop='^1' follow=on
bspc rule -a wpsoffice -o desktop='^3' follow=on
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Inkscape desktop='^4' state=floating follow=on
bspc rule -a Lxappearance desktop='^7' state=floating follow=on
bspc rule -a Arandr desktop='^7' follow=on

### NEED TO BE FLOATING ###
bspc rule -a URxvt state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Audacious state=floating follow=on
bspc rule -a Screenkey manage=off

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/bin/dual-monitor ];then
        dual-monitor
fi

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/local/bin/polybar ]; then
        bash $HOME/.config/polybar/launch.sh
fi
